[16.0][MIG] storage_backend_sftp: Migration to 16.0
OCA/storage pull request #241
Opened 2023-02-24 10:06 UTC by santostelmo

Migration of `storage_backend_sftp` to 16.0

2023-02-24 15:48 UTC, simahawk requested changes
please rewrite the commit msg as `[MIG] storage_backend_sftp: Migration to 16.0`

2023-02-24 15:48 UTC, simahawk commented on storage_backend_sftp/__manifest__.py
> +    "version": "16.0.1.0.2",
```suggestion
    "version": "16.0.1.0.0",
```

2023-02-27 07:14 UTC, santostelmo commented
> please rewrite the commit msg as `[MIG] storage_backend_sftp: Migration to 16.0`

done

2023-03-07 09:06 UTC, leemannd approved these changes

2023-03-23 13:47 UTC, bealdav commented
@simahawk finally message commit rename with your expectations. Final review ?

2023-03-27 13:26 UTC, MiquelRForgeFlow commented
Please cherry-pick https://github.com/OCA/storage/commit/cd5eddae1e7279674bd9ee0d20a1d11bac5ef03c, which was merged in v15.

2023-05-23 15:46 UTC, yvaucher commented
/ocabot migration storage_backend_sftp

2023-08-21 12:50 UTC, lmignon commented
A rewrite of the storage_backend_* is proposed as a single addon supporting a wider list of platform through the use of the fsscpec python lib. You can take a look here https://github.com/OCA/storage/pull/252 and https://github.com/OCA/storage/pull/251

2024-02-09 10:35 UTC, gurneyalex commented
@MiquelRForgeFlow The fix you are mentioning is on a different addon (storage_backend_ftp)

2024-02-09 10:59 UTC, gurneyalex approved these changes

2024-02-09 11:00 UTC, gurneyalex commented
/ocabot merge nobump

2024-02-09 11:22 UTC, gurneyalex commented
/ocabot merge nobump

2024-02-09 11:27 UTC, merged