[14.0][IMP] storage_image: Add a wizard to replace related file
OCA/storage pull request #273
Opened 2023-08-23 15:17 UTC by mmequignon

Adds a wizard on the image form to replace the attached file.

2023-08-24 06:04 UTC, simahawk requested changes
Thanks for the improvement :)

Can you
1. split commit by module
2. add the wizard to storage_media too
3. drop the funny image
4. drop the onchange approach

please? :smile:

2023-08-24 06:04 UTC, simahawk commented on storage_file/wizards/replace_file.py
> +    def onchange_data(self):
why on onchange? This is going to cause the creation of tons of orphan files IMO

2023-08-24 11:00 UTC, mmequignon commented
> Thanks for the improvement :)
> 
> Can you
> 
>     1. add the wizard to storage_media too
> 
>     2. drop the onchange approach
> 
>     3. split commit by module
> 
>     4. drop the funny image
> 
>     5. fix pre-commit
> 
> 
> please? 😄

baaah, you're not funny

2023-08-24 13:55 UTC, simahawk reviewed
LG, pls drop the icon. It's automatically generated ;)

2023-08-29 07:51 UTC, TDu reviewed
Some `tests` directory are missing an `__init__.py` file

2023-08-29 07:51 UTC, TDu commented on storage_file/wizards/replace_file.py
> +    _description = "TODO"
?

2023-08-29 07:51 UTC, TDu commented on storage_image/tests/test_storage_replace_file.py
> +# Copyright 2023 Camptocamp SA
`__init__.py` file is needed in the directory for the tests to be run on Travis

2024-07-12 06:29 UTC, simahawk approved these changes

2024-07-12 06:44 UTC, simahawk commented
@TDu could you update your review pls?

2024-07-12 06:53 UTC, TDu approved these changes

2024-07-15 08:25 UTC, simahawk commented
/ocabot merge minor

2024-07-15 08:31 UTC, merged