[FIX] fs_image: rawCacheKey is properly managed by STD
OCA/storage pull request #305
Opened 2023-11-29 14:24 UTC by sbejaoui

cc/ @lmignon

2023-11-29 15:12 UTC, lmignon commented
@sbejaoui  can you add a fragment to include into the addon history... as it's done here https://github.com/OCA/storage/pull/304/files#diff-0c0256bf7a5f02140833fcc325442a42553aac6aaf8b013258f347d6ce2d7e8c

2023-11-30 08:30 UTC, lmignon commented on fs_image/static/src/views/fields/fsimage_field.esm.js
> -            if (!this.rawCacheKey) {
@sbejaoui In both cases we redefine a method and don't call super. We should therefore process the 'rawCacheKey'

2023-12-02 08:30 UTC, lmignon commented on fs_image/static/src/views/fields/fsimage_field.esm.js
> -            if (!this.rawCacheKey) {
OK my Odoo was not up to date. Indeed, the 'rawCacheKey' is now a property

2023-12-02 08:52 UTC, sbejaoui commented
> @sbejaoui can you add a fragment to include into the addon history... as it's done here https://github.com/OCA/storage/pull/304/files#diff-0c0256bf7a5f02140833fcc325442a42553aac6aaf8b013258f347d6ce2d7e8c

done

2023-12-02 08:57 UTC, lmignon requested changes

2023-12-02 08:57 UTC, lmignon commented on fs_image/readme/newsfragments/305.bugfix
> +Remove rawCacheKey invalidation.
@sbejaoui Thank you for this changelog.  A little question. As a non developer or without having done this change, do you think this change can help to know if you need to update your addon? IMO, the title should explain for the end user what's this PR fixes.

2023-12-02 09:10 UTC, lmignon approved these changes

2023-12-02 09:10 UTC, lmignon commented
/ocabot merge patch

2023-12-02 09:13 UTC, merged