fs_attachment: sent the mimetype information for S3
OCA/storage pull request #354
Opened 2024-03-15 09:13 UTC by sebastienbeau

2024-06-24 13:45 UTC, vincent-hatakeyama commented
Cherry picked in 17.0 to test with a local minio, mimetype is now correctly set.

2024-06-26 06:51 UTC, lmignon requested changes

2024-06-26 06:51 UTC, lmignon commented on fs_attachment/models/ir_attachment.py
> +            return {"ContentType": self._context["mimetype"]}
the s3 fs could be nested at a deeper level... IMO you should recursively test the nested fs. Something like:

```
_fs = fs
while _fs:
    if hasattr(_fs, "s3"):
        return {"ContentType": self._context["mimetype"]}
    _fs = getattr(_fs, "fs", None)
```

2024-11-10 10:49 UTC, lmignon commented
superseded by #378

2024-11-10 10:49 UTC, closed without merging

2025-07-30 10:45 UTC, sbidoul commented
heads-up, in #497 this is moving to a separate fs_attachment_s3 module